### PR TITLE
Setup `google/gts` linter.

### PR DESCRIPTION
**Pull request by narekhovhannisyan**
### Types of changes

- [x] Enhancement (project structure, spelling, grammar, formatting)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### A description of the changes proposed in the Pull Request

- Setup `google/gts`, `fixpack` libs.
- Applied linter to whole project.
- Added pull request template.
- Mentioned engine in package.json file.

### CODE REVIEW

**Comment by jawache** [comment]
Thanks @narekhovhannisyan looks good to me. Is the plan to run the linter against a PR and report if it doesn't match, or should we just have a good practice of running the linter before checkin?

**Review by jawache — APPROVED** [review]

**Comment by narekhovhannisyan** [comment]
Since remembering and linting code locally is depending on programmer, it's better to check it in CI/CD for being sure that everything is ok on merge.

**Review by gnanakeethan — APPROVED** [review]
LGTM

**Comment by narekhovhannisyan** [comment]
#77

**Pull request merged**
